// src/firebase-init.ts

import { initializeApp } from "firebase/app";
import { getMessaging, getToken, onMessage } from "firebase/messaging";

// --- PASTE YOUR FIREBASE CONFIG OBJECT FROM STEP 1 HERE ---
const firebaseConfig = {
  apiKey: "AIzaSyAB6luds9Z-Luc_T4Of4qNQrRe9Oh7Pt8Q",
  authDomain: "marudhar-school-erp.firebaseapp.com",
  projectId: "marudhar-school-erp",
  storageBucket: "marudhar-school-erp.firebasestorage.app",
  messagingSenderId: "400371137837",
  appId: "1:400371137837:web:c8a7bbed749f2d1029a7a4"
};
// -------------------------------------------------------------

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

// --- Function to request permission and get the token ---
export const requestForToken = async () => {
  try {
    const currentToken = await getToken(messaging, { 
      // This VAPID key is generated by Firebase in the background
      vapidKey: "YOUR_VAPID_KEY_FROM_FIREBASE_SETTINGS", 
    });
    if (currentToken) {
      console.log('FCM Registration Token:', currentToken);
      // **IMPORTANT**: This is the token you will need to save to your database.
      // We will handle saving it in a later step.
      return currentToken;
    } else {
      console.log('No registration token available. Request permission to generate one.');
      alert('Please enable notifications to receive important school updates.');
      return null;
    }
  } catch (err) {
    console.error('An error occurred while retrieving token. ', err);
    return null;
  }
};

// --- Function to listen for foreground messages ---
export const onMessageListener = () =>
  new Promise((resolve) => {
    onMessage(messaging, (payload) => {
      console.log('Foreground message received. ', payload);
      // We will build a UI to show this notification later
      resolve(payload);
    });
  });